Index: ChangeLog from  Raphaël Poss  <raph@lrde.epita.fr>    * vcsn.m4: Rename to...    * config/vcsn.m4: this.
   * config/vcsn.m4 (AC_WITH_VCSN): Add more macros.
   * configure.ac: Sanitize. Adapt to new configuration system.
   * Makefile.am: Sanitize. Comment more.
   * src/Makefile.am (SUBDIRS): Mention `demos'.

   * include/vaucanson/config/system.hh: Adapt to new configuration
   system.

   * src/tests/bin/generate-test-suite.sh: Sanitize.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,15 +3,46 @@
 #
 # $Id$
 
-AUTOMAKE_OPTIONS = foreign 1.6
-SUBDIRS = include src doc vauc
-EXTRA_DIST = THANKS README LICENCE ChangeLog tools/scandefs.pl vcsn.m4
+AUTOMAKE_OPTIONS = foreign 1.7
+
+SUBDIRS = include src doc 
+
+EXTRA_DIST = THANKS README LICENCE 
+
+###
+### Autoconf needs additional macros. 
+### Tell it where to find them.
+###
+ACLOCAL_AMFLAGS = -I config
+CONFIGURE_DEPENDENCIES = $(srcdir)/config/vcsn.m4
+EXTRA_DIST += config/vcsn.m4
+
+###
+### Autoconf macros are installable.
+###
+
+m4datadir = $(datadir)/aclocal
+dist_m4data_DATA = config/vcsn.m4
+
+###
+### Check headers for sanity.
+###
+
+# This is totally experimental. Comments are welcome.
+maintainer-check:
+	if cppi --version >/dev/null 2>&1; then \
+	  find $(srcdir) -name '*.{cc,hh,hxx}' | \
+	    xargs cppi --check; \
+	else \
+	  echo "$@: GNU cppi is required" >&2; \
+	fi
+
+###
+### Documentation generation: add `doc' target for convenience.
+###
 
 .PHONY: doc
 
 doc:
 	cd doc && $(MAKE) doc
-
-ACLOCAL_AMFLAGS = -I .
-CONFIGURE_DEPENDENCIES = $(srcdir)/vcsn.m4
 
