Update texi2dvi.
	Now that texi2dvi supports --dvipdf, we no longer need
	manual.mk.  As a benefit (err, target actually), it will be easier 
	to generate several outputs from a single source (say including
	or not the developer sections).
	* doc/manual.mk: Remove.
	* doc/xml/Makefile.am, doc/manual/Makefile.am: Adjust.

diff --git a/doc/share/bin/texi2dvi b/doc/share/bin/texi2dvi
--- a/doc/share/bin/texi2dvi
+++ b/doc/share/bin/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.77 2006/03/13 16:47:33 karl Exp $
+# $Id: texi2dvi,v 1.84 2006/06/19 09:35:01 akim Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
 # 2002, 2003, 2004, 2005, 2006 Free Software Foundation, Inc.
@@ -35,7 +35,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.77 $'
+rcs_revision='$Revision: 1.84 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -79,6 +79,7 @@ General options:
 
 TeX tuning:
   -@                         use @input instead of \input for preloaded Texinfo
+      --dvi                  output a DVI file [default]
   -e, -E, --expand           force macro expansion using makeinfo
   -I DIR                     search DIR for Texinfo files
   -l, --language=LANG        specify the LANG of FILE (LaTeX or Texinfo)
@@ -86,6 +87,7 @@ TeX tuning:
   -p, --pdf                  use pdftex or pdflatex for processing
   -r, --recode               call recode before TeX to translate input
       --recode-from=ENC      recode from ENC to the @documentencoding
+      --src-specials         pass --src-specials to TeX
   -t, --command=CMD          insert CMD in copy of input file
    or --texinfo=CMD          multiple values accumulate
       --translate-file=FILE  use given charset translation file for TeX
@@ -156,6 +158,7 @@ out_lang=dvi
 quiet=false     # by default let the tools' message be displayed
 recode=false
 set_language=
+src_specials=
 textra=         # Extra TeX commands to insert in the input file.
 txiprereq=19990129 # minimum texinfo.tex version with macro expansion
 verb=false      # true for verbose mode
@@ -163,6 +166,16 @@ translate_file= # name of charset translation file
 recode_from=    # if not empty, recode from this encoding to @documentencoding
 
 orig_pwd=`pwd`
+
+# We have to initialize IFS to space tab newline since we save and
+# restore IFS and apparently POSIX allows stupid/broken behavior with
+# empty-but-set IFS.
+# http://lists.gnu.org/archive/html/automake-patches/2006-05/msg00008.html
+# We need space, tab and new line, in precisely that order.  And don't leave
+# trailing blanks.
+newline='
+'
+IFS=" 	$newline"
 
 # Systems which define $COMSPEC or $ComSpec use semicolons to separate
 # directories in TEXINPUTS -- except for Cygwin, where COMSPEC might be
@@ -382,6 +395,38 @@ list_dir_to_abs ()
   eval $ld_l=\"$@\"
 }
 
+
+## ------------------------------ ##
+## Language auxiliary functions.  ##
+## ------------------------------ ##
+
+# out_lang_tex
+# ------------
+# Return the tex output language (DVI or PDF) for $OUT_LANG.
+out_lang_tex ()
+{
+  case $out_lang in
+    dvi | ps | dvipdf ) echo dvi;;
+    pdf ) echo $out_lang;;
+    html | info | text ) echo $out_lang;;
+    *)    fatal "$0: invalid out_lang: $1";;
+  esac
+}
+
+
+# out_lang_ext
+# ------------
+# Return the extension for $OUT_LANG.
+out_lang_ext ()
+{
+  case $out_lang in
+    dvipdf ) echo pdf;;
+    dvi | html | info | pdf | ps | text ) echo $out_lang;;
+    *)    fatal "$0: invalid out_lang: $1";;
+  esac
+}
+
+
 ## ------------------------- ##
 ## TeX auxiliary functions.  ##
 ## ------------------------- ##
@@ -489,7 +534,7 @@ aux_file_p ()
 # ------------------
 # Return with success with FILE is an aux file containing citation
 # requests.
-aux_file_p ()
+bibaux_file_p ()
 {
   test -s "$1" || return 1
   if (grep '^\\bibstyle[{]' "$1"   \
@@ -555,7 +600,7 @@ generated_files_get ()
   # Depending on these files, infer outputs from other tools.
   while read file; do
     echo $file
-    case $language in
+    case $in_lang in
       (texinfo)
         # texindex: texinfo.cp -> texinfo.cps
        if index_file_p $file; then
@@ -644,12 +689,14 @@ xref_files_changed ()
 ## Running the TeX suite.  ##
 ## ----------------------- ##
 
+
+
 # run_tex ()
 # ----------
 # Run TeX as "$tex $in_input", taking care of errors and logs.
 run_tex ()
 {
-  case $language:$out_lang in
+  case $in_lang:$(out_lang_tex) in
     latex:dvi)   tex=${LATEX:-latex};;
     latex:pdf)   tex=${PDFLATEX:-pdflatex};;
     texinfo:dvi)
@@ -661,12 +708,12 @@ run_tex ()
         esac;;
     texinfo:pdf) tex=$PDFTEX;;
 
-    *) fatal 1 "$out_lang not supported for $language";;
+    *) fatal 1 "$0: $out_lang not supported for $in_lang";;
   esac
 
   # Beware of aux files in subdirectories that require the
   # subdirectory to exist.
-  case $language:$tidy in
+  case $in_lang:$tidy in
     latex:true)
        sed -n 's|^[ ]*\\include{\(.*\)/.*}.*|\1|p' "$in_input" |
        sort -u |
@@ -699,6 +746,10 @@ run_tex ()
   # Tell TeX about TCX file, if specified.
   test -n "$translate_file" && cmd="$cmd --translate-file=$translate_file"
 
+  # Tell TeX to make source specials (for backtracking from output to
+  # source, given a sufficiently smart editor), if specifed.
+  test -n "$src_specials" && cmd="$cmd $src_specials"
+
   # Tell TeX to be batch if requested.
   if $batch; then
     # \batchmode does not show terminal output at all, so we don't
@@ -726,9 +777,11 @@ run_tex ()
       ;;
   esac
 
-  verbose "Running $cmd ..."
+  echo "$0: Running $cmd ..."
   if eval "$cmd" >&5; then
-    move_to_dest "$in_noext.$out_lang"
+    case $out_lang in
+      dvi | pdf ) move_to_dest "$in_noext.$out_lang";;
+    esac
   else
     fatal 1 "$tex exited with bad status, quitting."
   fi
@@ -752,7 +805,7 @@ run_tex ()
 # easier, though we take the risk to match false messages.
 run_bibtex ()
 {
-  case $language in
+  case $in_lang in
     latex)   bibtex=${BIBTEX:-bibtex};;
     texinfo) return;;
   esac
@@ -765,21 +818,11 @@ run_bibtex ()
           || grep 'No file .*\.bbl\.' "$in_noext.log") \
         >&6 2>&1; \
   then
-    generated_files_get "$in_noext" |
-    while read f
+    for f in $(generated_files_get "$in_noext" bibaux_file_p)
     do
-      if test -s "$f" && \
-         (grep '^\\bibstyle[{]' "$f"   \
-          && grep '^\\bibdata[{]' "$f" \
-	  ## The following line is suspicious: fails when there
-          ## are citations in sub aux files.  We need to be
-          ## smarter in this case.
-          ## && grep '^\\citation[{]' "$f"
-	  ) >&6 2>&1; then
-        verbose "Running $bibtex $f ..."
-        $bibtex "$f" >&5 ||
-          fatal 1 "$bibtex exited with bad status, quitting."
-      fi
+      verbose "Running $bibtex $f ..."
+      $bibtex "$f" >&5 ||
+        fatal 1 "$bibtex exited with bad status, quitting."
     done
   fi
 }
@@ -792,7 +835,7 @@ run_bibtex ()
 # that if the index files are out of date or nonexistent.
 run_index ()
 {
-  case $language in
+  case $in_lang in
     latex)   texindex=${MAKEINDEX:-makeindex};;
     texinfo) texindex=${TEXINDEX:-texindex};;
   esac
@@ -809,7 +852,7 @@ run_index ()
 # ---------------
 run_thumbpdf ()
 {
-  if test $out_lang = pdf \
+  if test $(out_lang_tex) = pdf \
      && test -r "$in_noext.log" \
      && grep 'thumbpdf\.sty'  "$in_noext.log" >&6 2>&1; \
   then
@@ -852,6 +895,19 @@ run_tex_suite ()
   # If we were using thumbpdf and producing PDF, then run thumbpdf
   # and TeX one last time.
   run_thumbpdf
+
+  # Install the result if we didn't already (i.e., if the output is
+  # dvipdf or ps).
+  case $out_lang in
+    dvipdf)
+      dvipdf "$in_noext.$(out_lang_tex)" "$in_noext.$(out_lang_ext)"
+      move_to_dest "$in_noext.$(out_lang_ext)"
+      ;;
+    ps)
+      dvips -o "$in_noext.$(out_lang_ext)" "$in_noext.$(out_lang_tex)"
+      move_to_dest "$in_noext.$(out_lang_ext)"
+      ;;
+  esac
 }
 
 ## -------------------------------- ##
@@ -901,7 +957,7 @@ uncomment_iftex='s/^@c texi2dvi//'
 # main info output, the user asked to run TeX, not makeinfo.
 run_makeinfo ()
 {
-  case $language in
+  case $in_lang in
   texinfo)
     # Unless required by the user, makeinfo expansion is wanted only
     # if texinfo.tex is too old.
@@ -921,7 +977,7 @@ run_makeinfo ()
          echo '\input texinfo.tex @bye' >txiversion.tex
          # Be sure that if tex wants to fail, it is not interactive:
          # close stdin.
-         tex txiversion.tex </dev/null >txiversion.out 2>txiversion.err
+         $TEX txiversion.tex </dev/null >txiversion.out 2>txiversion.err
       )
       if test $? != 0; then
         cat $version_test_dir/txiversion.out
@@ -975,10 +1031,10 @@ run_makeinfo ()
 insert_commands ()
 {
   local textra_cmd
-  case $language in
+  case $in_lang in
     latex)   textra_cmd=1i;;
     texinfo) textra_cmd='/^@setfilename/a';;
-    *)       echo "$0: internal error, unknown language: $language" >&2;
+    *)       echo "$0: internal error, unknown language: $in_lang" >&2;
   esac
 
   if test -n "$textra"; then
@@ -1002,7 +1058,7 @@ run_recode ()
   local from
   local to
 
-  if test $language = texinfo; then
+  if test $in_lang = texinfo; then
     pgm='s/^ *@documentencoding  *\([^ ][^ ]*\) *$/\1/
 	t found
 	d
@@ -1096,9 +1152,13 @@ run_core_conversion ()
     cd "$work_build" || exit 1
   fi
 
-  case $out_lang in
-    dvi|pdf)        run_tex_suite;;
-    html|text|info) run_hevea $out_lang;;
+  case $in_lang:$(out_lang_tex) in
+    *:dvi|*:pdf)
+	run_tex_suite;;
+    latex:html|latex:text|latex:info)
+	run_hevea $out_lang;;
+    *)
+	fatal "invalid input/output combination: $in_lang/$out_lang";;
   esac
 
   cd_orig
@@ -1221,6 +1281,8 @@ while test x"$1" != x"$arg_sep"; do
          --build-dir)  shift; build_dir=$1; build_mode=tidy;;
     -c | --clean) build_mode=clean;;
     -D | --debug) debug=true;;
+         --dvi)   out_lang=dvi;;
+         --dvipdf)   out_lang=dvipdf;;
     -e | -E | --expand) expand=t;;
     -h | --help) echo "$usage"; exit 0;;
          --html) out_lang=html;;
@@ -1239,9 +1301,11 @@ while test x"$1" != x"$arg_sep"; do
       # Make it absolute, just in case we also have --clean, or whatever.
       oname=`absolute "$1"`;;
     -p | --pdf) out_lang=pdf;;
+         --ps)  out_lang=ps;;
     -q | -s | --quiet | --silent) quiet=true; batch=true;;
     -r | --recode) recode=true;;
     --recode-from) shift; recode=true; recode_from="$1";;
+    --src-specials) src_specials=--src-specials;;
     -t | --texinfo | --command ) shift; textra="$textra\\
 "`echo "$1" | sed 's/\\\\/\\\\\\\\/g'`;;
     --text) out_lang=text;;
@@ -1423,7 +1487,7 @@ input_file_name_decode ()
   if test x"$oname" != x; then
     out_name=$oname
   else
-    out_name=$in_noext.$out_lang
+    out_name=$in_noext.$(out_lang_ext)
   fi
   out_dir=`func_dirname "$out_name"`
   out_dir_abs=`absolute "$out_dir"`
@@ -1442,7 +1506,7 @@ for command_line_filename in ${1+"$@"}; do
   input_file_name_decode
 
   # `texinfo' or `latex'?
-  language=`compute_language $command_line_filename`
+  in_lang=`compute_language $command_line_filename`
 
   # An auxiliary directory used for all the auxiliary tasks involved
   # in compiling this document.
@@ -1465,7 +1529,7 @@ for command_line_filename in ${1+"$@"}; do
   # Sometimes there are incompatibilities between auxiliary files for
   # DVI and PDF.  The contents can also change whether we work on PDF
   # and/or DVI.  So keep separate spaces for each.
-  workdir=$t2ddir/$out_lang
+  workdir=$t2ddir/$(out_lang_tex)
   ensure_dir "$workdir"
 
   # _build.  In a tidy build, where the auxiliary files are output.
