2006-07-21  Akim Demaille  <akim@epita.fr>
	Automatically generate bit of the documentation using TAF-Kit.
	* doc/manual/extex.mk, doc/manual/extex.pl: New.
	* doc/manual/Makefile.am: Use them to extract commands to be run
	before compiling the LaTeX file.
	* doc/manual/vaucanson-user-manual.tex (legend): New.
	* doc/manual/taf-kit.tex (\includegenerateddot, \execcaption):
	New.

diff --git a/doc/share/bin/texi2dvi b/doc/share/bin/texi2dvi
--- a/doc/share/bin/texi2dvi
+++ b/doc/share/bin/texi2dvi
@@ -1,6 +1,6 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.84 2006/06/19 09:35:01 akim Exp $
+# $Id: texi2dvi,v 1.89 2006/06/27 17:01:26 akim Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
 # 2002, 2003, 2004, 2005, 2006 Free Software Foundation, Inc.
@@ -35,7 +35,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.84 $'
+rcs_revision='$Revision: 1.89 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -251,7 +251,7 @@ absolute ()
       if test -d "$rel"; then
         (cd "$rel" 2>/dev/null && echo `pwd`/`basename "$1"`);
       else
-        fatal 1 "not a directory: $rel"
+        error 1 "not a directory: $rel"
       fi
       ;;
   esac
@@ -295,6 +295,8 @@ report ()
   done
 }
 
+# verbose WORD1 WORD2
+# -------------------
 # Report some verbose information.
 verbose ()
 {
@@ -303,15 +305,28 @@ verbose ()
   fi
 }
 
-# fatal EXIT_STATUS LINE1 LINE2...
-# --------------------------------
-# Report an error and exit with failure.
-fatal ()
+# run COMMAND-LINE
+# ----------------
+# Run the COMMAND-LINE verbosely, and catching errors as failures.
+run ()
 {
-  s=$1
+  verbose "Running $@"
+  "$@" 2>&5 1>&2 ||
+     error 1 "$1 failed"
+}
+
+
+# error EXIT_STATUS LINE1 LINE2...
+# --------------------------------
+# Report an error and exit with failure if EXIT_STATUS is non null.
+error ()
+{
+  local s=$1
   shift
   report "$@"
-  exit $s
+  if test "$s" != 0; then
+    exit $s
+  fi
 }
 
 # ensure_dir DIR1 DIR2...
@@ -323,7 +338,7 @@ ensure_dir ()
   do
     test -d "$dir" \
       || mkdir "$dir" \
-      || fatal 1 "cannot create directory: $dir"
+      || error 1 "cannot create directory: $dir"
   done
 }
 
@@ -409,7 +424,7 @@ out_lang_tex ()
     dvi | ps | dvipdf ) echo dvi;;
     pdf ) echo $out_lang;;
     html | info | text ) echo $out_lang;;
-    *)    fatal "$0: invalid out_lang: $1";;
+    *)    error 1 "$0: invalid out_lang: $1";;
   esac
 }
 
@@ -422,7 +437,7 @@ out_lang_ext ()
   case $out_lang in
     dvipdf ) echo pdf;;
     dvi | html | info | pdf | ps | text ) echo $out_lang;;
-    *)    fatal "$0: invalid out_lang: $1";;
+    *)    error 1 "$0: invalid out_lang: $1";;
   esac
 }
 
@@ -490,8 +505,9 @@ output_base_name ()
   esac
 }
 
-# move_to_dest FILE
-# -----------------
+
+# move_to_dest FILE...
+# --------------------
 # Move the FILE to the place where the user expects it.  FILE can be
 # the principal output (in which case -o directly apply), or an auxiliary
 # file with the same base name.
@@ -499,18 +515,21 @@ move_to_dest ()
 {
   local dest
 
-  case $tidy:$oname in
-    true:)  dest=$orig_pwd;;
-    false:) dest=;;
-    *:*)    dest=$(output_base_name "$1");;
-  esac
-  if test ! -f "$1"; then
-    fatal 1 "no such file or directory: $1"
-  fi
-  if test -n "$dest"; then
-    verbose "Copying $1 to $dest"
-    cp -p "$1" "$dest"
-  fi
+  for file
+  do
+    case $tidy:$oname in
+      true:)  dest=$orig_pwd;;
+      false:) dest=;;
+      *:*)    dest=$(output_base_name "$file");;
+    esac
+    if test ! -f "$file"; then
+      error 1 "no such file or directory: $file"
+    fi
+    if test -n "$dest"; then
+      verbose "Copying $file to $dest"
+      cp -p "$file" "$dest"
+    fi
+  done
 }
 
 
@@ -622,7 +641,9 @@ generated_files_get ()
       echo $file
     fi
   done |
-  sort
+  sort |
+  # Some files are opened several times, e.g., listings.sty's *.vrb.
+  uniq
 }
 
 
@@ -708,7 +729,7 @@ run_tex ()
         esac;;
     texinfo:pdf) tex=$PDFTEX;;
 
-    *) fatal 1 "$0: $out_lang not supported for $in_lang";;
+    *) error 1 "$0: $out_lang not supported for $in_lang";;
   esac
 
   # Beware of aux files in subdirectories that require the
@@ -783,7 +804,7 @@ run_tex ()
       dvi | pdf ) move_to_dest "$in_noext.$out_lang";;
     esac
   else
-    fatal 1 "$tex exited with bad status, quitting."
+    error 1 "$tex exited with bad status, quitting."
   fi
 }
 
@@ -820,9 +841,7 @@ run_bibtex ()
   then
     for f in $(generated_files_get "$in_noext" bibaux_file_p)
     do
-      verbose "Running $bibtex $f ..."
-      $bibtex "$f" >&5 ||
-        fatal 1 "$bibtex exited with bad status, quitting."
+      run $bibtex "$f"
     done
   fi
 }
@@ -841,9 +860,7 @@ run_index ()
   esac
   index_files=`generated_files_get $in_noext index_file_p`
   if test -n "$texindex" && test -n "$index_files"; then
-    verbose "Running $texindex $index_files ..."
-    $texindex $index_files 2>&5 1>&2 ||
-       fatal 1 "$texindex exited with bad status, quitting."
+    run $texindex $index_files
   fi
 }
 
@@ -868,11 +885,40 @@ run_thumbpdf ()
 }
 
 
+# run_dvipdf FILE.dvi
+# -------------------
+# Convert FILE.dvi to FILE.pdf.
+run_dvipdf ()
+{
+  # Find which dvi->pdf program is available.
+  if test -z "$dvipdf"; then
+    for i in "$DVIPDF" dvipdfmx dvipdfm dvipdf dvi2pdf dvitopdf;
+    do
+      if findprog $i; then
+        dvipdf=$i
+      fi
+    done
+  fi
+  # These tools have varying interfaces, some 'input output', others
+  # 'input -o output'.  They all seem to accept 'input' only,
+  # outputting using the expected file name.
+  run $dvipdf "$1"
+  if test ! -f $(echo "$1" | sed -e 's/\.dvi$/.pdf/'); then
+    error 1 "$0: cannot find output file"
+  fi
+}
+
 # run_tex_suite ()
 # ----------------
 # Run the TeX tools until a fix point is reached.
 run_tex_suite ()
 {
+  # Move to the working directory.
+  if $tidy; then
+    verbose "cd $work_build"
+    cd "$work_build" || exit 1
+  fi
+
   # Count the number of cycles.
   local cycle=0
 
@@ -887,7 +933,7 @@ run_tex_suite ()
     # converse.
     run_bibtex
     run_index
-    run_tex
+    run_core_conversion
 
     xref_files_changed || break
   done
@@ -900,7 +946,7 @@ run_tex_suite ()
   # dvipdf or ps).
   case $out_lang in
     dvipdf)
-      dvipdf "$in_noext.$(out_lang_tex)" "$in_noext.$(out_lang_ext)"
+      run_dvipdf "$in_noext.$(out_lang_tex)"
       move_to_dest "$in_noext.$(out_lang_ext)"
       ;;
     ps)
@@ -908,6 +954,8 @@ run_tex_suite ()
       move_to_dest "$in_noext.$(out_lang_ext)"
       ;;
   esac
+
+  cd_orig
 }
 
 ## -------------------------------- ##
@@ -957,72 +1005,71 @@ uncomment_iftex='s/^@c texi2dvi//'
 # main info output, the user asked to run TeX, not makeinfo.
 run_makeinfo ()
 {
-  case $in_lang in
-  texinfo)
-    # Unless required by the user, makeinfo expansion is wanted only
-    # if texinfo.tex is too old.
-    if test "$expand" = t; then
-      makeinfo=${MAKEINFO:-makeinfo}
-    else
-      # Check if texinfo.tex performs macro expansion by looking for
-      # its version.  The version is a date of the form YEAR-MO-DA.
-      # We don't need to use [0-9] to match the digits since anyway
-      # the comparison with $txiprereq, a number, will fail with non
-      # digits.
-      # Run in a temporary directory to avoid leaving files.
-      version_test_dir=$t2ddir/version_test
-      ensure_dir "$version_test_dir"
-      (
-         cd "$version_test_dir"
-         echo '\input texinfo.tex @bye' >txiversion.tex
-         # Be sure that if tex wants to fail, it is not interactive:
-         # close stdin.
-         $TEX txiversion.tex </dev/null >txiversion.out 2>txiversion.err
-      )
-      if test $? != 0; then
-        cat $version_test_dir/txiversion.out
-        cat $version_test_dir/txiversion.err >&2
-        fatal 1 "texinfo.tex appears to be broken, quitting."
-      fi
-      eval `sed -n 's/^.*\[\(.*\)version \(....\)-\(..\)-\(..\).*$/txiformat=\1 txiversion="\2\3\4"/p' $version_test_dir/txiversion.out`
-      verbose "texinfo.tex preloaded as \`$txiformat', version is \`$txiversion' ..."
-      if test "$txiprereq" -le "$txiversion" >&6 2>&1; then
-        makeinfo=
-      else
-        makeinfo=${MAKEINFO:-makeinfo}
-      fi
-      # As long as we had to run TeX, offer the user this convenience:
-      if test "$txiformat" = Texinfo; then
-	escape=@
-      fi
-    fi
+  test $in_lang == texinfo ||
+    return 0
 
-    if test -n "$makeinfo"; then
-      # in_src: the file with macros expanded.
-      # Use the same basename to generate the same aux file names.
-      work_src=$workdir/src
-      ensure_dir "$work_src"
-      in_src=$work_src/$in_base
-      local miincludes=`list_prefix includes -I`
-      verbose "Macro-expanding $command_line_filename to $in_src ..."
-      # eval $makeinfo because it might be defined as something complex
-      # (running missing) and then we end up with things like '"-I"',
-      # and "-I" (including the quotes) is not an option name.  This
-      # happens with gettext 0.14.5, at least.
-      sed "$comment_iftex" "$command_line_filename" \
-        | eval $makeinfo --footnote-style=end -I "$in_dir" $miincludes \
-          -o /dev/null --macro-expand=- \
-        | sed "$uncomment_iftex" >"$in_src"
-      # Continue only if everything succeeded.
-      if test $? -ne 0 \
-         || test ! -r "$in_src"; then
-        verbose "Expansion failed, ignored...";
-      else
-        in_input=$in_src
-      fi
+  # Unless required by the user, makeinfo expansion is wanted only
+  # if texinfo.tex is too old.
+  if test "$expand" = t; then
+    makeinfo=${MAKEINFO:-makeinfo}
+  else
+    # Check if texinfo.tex performs macro expansion by looking for
+    # its version.  The version is a date of the form YEAR-MO-DA.
+    # We don't need to use [0-9] to match the digits since anyway
+    # the comparison with $txiprereq, a number, will fail with non
+    # digits.
+    # Run in a temporary directory to avoid leaving files.
+    version_test_dir=$t2ddir/version_test
+    ensure_dir "$version_test_dir"
+    (
+       cd "$version_test_dir"
+       echo '\input texinfo.tex @bye' >txiversion.tex
+       # Be sure that if tex wants to fail, it is not interactive:
+       # close stdin.
+       $TEX txiversion.tex </dev/null >txiversion.out 2>txiversion.err
+    )
+    if test $? != 0; then
+      cat $version_test_dir/txiversion.out
+      cat $version_test_dir/txiversion.err >&2
+      error 1 "texinfo.tex appears to be broken, quitting."
     fi
-    ;;
-  esac
+    eval `sed -n 's/^.*\[\(.*\)version \(....\)-\(..\)-\(..\).*$/txiformat=\1 txiversion="\2\3\4"/p' $version_test_dir/txiversion.out`
+    verbose "texinfo.tex preloaded as \`$txiformat', version is \`$txiversion' ..."
+    if test "$txiprereq" -le "$txiversion" >&6 2>&1; then
+      makeinfo=
+    else
+      makeinfo=${MAKEINFO:-makeinfo}
+    fi
+    # As long as we had to run TeX, offer the user this convenience:
+    if test "$txiformat" = Texinfo; then
+	escape=@
+    fi
+  fi
+
+  if test -n "$makeinfo"; then
+    # in_src: the file with macros expanded.
+    # Use the same basename to generate the same aux file names.
+    work_src=$workdir/src
+    ensure_dir "$work_src"
+    in_src=$work_src/$in_base
+    local miincludes=`list_prefix includes -I`
+    verbose "Macro-expanding $command_line_filename to $in_src ..."
+    # eval $makeinfo because it might be defined as something complex
+    # (running missing) and then we end up with things like '"-I"',
+    # and "-I" (including the quotes) is not an option name.  This
+    # happens with gettext 0.14.5, at least.
+    sed "$comment_iftex" "$command_line_filename" \
+      | eval $makeinfo --footnote-style=end -I "$in_dir" $miincludes \
+        -o /dev/null --macro-expand=- \
+      | sed "$uncomment_iftex" >"$in_src"
+    # Continue only if everything succeeded.
+    if test $? -ne 0 \
+       || test ! -r "$in_src"; then
+      verbose "Expansion failed, ignored...";
+    else
+      in_input=$in_src
+    fi
+  fi
 }
 
 # insert_commands ()
@@ -1034,7 +1081,7 @@ insert_commands ()
   case $in_lang in
     latex)   textra_cmd=1i;;
     texinfo) textra_cmd='/^@setfilename/a';;
-    *)       echo "$0: internal error, unknown language: $in_lang" >&2;
+    *)       fatal 1 "internal error, unknown language: $in_lang";;
   esac
 
   if test -n "$textra"; then
@@ -1114,7 +1161,15 @@ compute_language ()
 
 # run_hevea (MODE)
 # ----------------
-# Convert to HTML.
+# Convert to HTML/INFO/TEXT.
+#
+# Don't pass `-noiso' to hevea: it's useless in HTML since anyway the
+# charset is set to latin1, and troublesome in other modes since
+# accented characters loose their accents.
+#
+# Don't pass `-o DEST' to hevea because in that case it leaves all its
+# auxiliary files there too...  Too bad, because it means we will need
+# to handle images some day.
 run_hevea ()
 {
   local hevea=${HEVEA:-hevea}
@@ -1123,45 +1178,45 @@ run_hevea ()
   case $1 in
     html) ;;
     text|info) run_hevea="$run_hevea -$1";;
-    *) fatal "run_hevea: invalid argument: $1";;
+    *) error 1 "run_hevea: invalid argument: $1";;
   esac
 
   # Compiling to the tmp directory enables to preserve a previous
-  # successful compilation.  Unfortunately it makes it hard to move
-  # the image back to the destination directory.  So compile to the
-  # actual destination.
-  run_hevea="$run_hevea -fix -noiso -O -o '$out_name'"
+  # successful compilation.
+  run_hevea="$run_hevea -fix -O -o '$out_base'"
   run_hevea="$run_hevea `list_prefix includes -I` -I '$orig_pwd' "
   run_hevea="$run_hevea '$in_input'"
 
+  if $debug; then
+    run_hevea="$run_hevea -v -v"
+  fi
+
   verbose "running $run_hevea"
-  if eval "$run_hevea" >&5; then :; else
-    fatal 1 "$hevea exited with bad status, quitting."
+  if eval "$run_hevea" >&5; then
+    case $1 in
+    html|text) move_to_dest "$out_base";;
+    info) # There can be foo.info-1, foo.info-2 etc.
+               move_to_dest "$out_base"*;;
+    esac
+  else
+    error 1 "$hevea exited with bad status, quitting."
   fi
 }
 
 
 # run_core_conversion ()
 # ----------------------
-# Run the TeX tools until a fix point is reached.
+# Run the TeX (or HeVeA).
 run_core_conversion ()
 {
-  # Move to the working directory.
-  if $tidy; then
-    verbose "cd $work_build"
-    cd "$work_build" || exit 1
-  fi
-
   case $in_lang:$(out_lang_tex) in
     *:dvi|*:pdf)
-	run_tex_suite;;
+	run_tex;;
     latex:html|latex:text|latex:info)
 	run_hevea $out_lang;;
     *)
-	fatal "invalid input/output combination: $in_lang/$out_lang";;
+	error 1 "invalid input/output combination: $in_lang/$out_lang";;
   esac
-
-  cd_orig
 }
 
 
@@ -1201,7 +1256,7 @@ compile ()
   run_recode
 
   # Run until a fix point is reached.
-  run_core_conversion
+  run_tex_suite
 }
 
 
@@ -1212,6 +1267,7 @@ remove ()
   verbose "Removing" "$@"
   rm -rf "$@"
 }
+
 
 # mostly_clean
 # ------------
@@ -1321,7 +1377,7 @@ while test x"$1" != x"$arg_sep"; do
       done
       break;;
     -*)
-      fatal 1 "Unknown or ambiguous option \`$1'." \
+      error 1 "Unknown or ambiguous option \`$1'." \
               "Try \`--help' for more information."
       ;;
     *) set dummy ${1+"$@"} "$1"; shift;;
@@ -1337,18 +1393,18 @@ case $build_mode in
   local) clean=false; tidy=false;;
   tidy)  clean=false; tidy=true;;
   clean) clean=true;  tidy=true;;
-      *) fatal 1 "invalid build mode: $build_mode";;
+      *) error 1 "invalid build mode: $build_mode";;
 esac
 
 # Interpret remaining command line args as filenames.
 case $# in
  0)
-  fatal 2 "Missing file arguments." "Try \`--help' for more information."
+  error 2 "Missing file arguments." "Try \`--help' for more information."
   ;;
  1) ;;
  *)
   if test -n "$oname"; then
-    fatal 2 "Can't use option \`--output' with more than one argument."
+    error 2 "Can't use option \`--output' with more than one argument."
   fi
   ;;
 esac
@@ -1463,7 +1519,7 @@ input_file_name_decode ()
   # prompt (assuming they're attending the terminal), this script won't
   # be able to find the right xref files and so forth.
   test  -r "$command_line_filename" ||
-    fatal 1 "cannot read $command_line_filename, skipping."
+    error 1 "cannot read $command_line_filename, skipping."
 
   # Get the name of the current directory.
   in_dir=`func_dirname "$command_line_filename"`
