More dev doc. 	* doc/manual/vaucanswig.tex: Add missing label. 	White space changes. 	* doc/manual/developer.tex (Maintainer Tools): Valgrind and 	libstdsc++.

diff --git a/doc/share/Makefile b/doc/share/Makefile
--- a/doc/share/Makefile
+++ b/doc/share/Makefile
@@ -1,2 +1,111 @@
-check:
-	LC_ALL=C grep '[^[:print:][:blank:]]' bib/*.bib || exit 0
+share_dir = .
+include make/share.mk
+include make/tex.mk
+
+QUIET = @
+papersdir = /lrde/doc/lrde/papers
+papers_DATA = lrde.pdf lrde-private.pdf README-lrde.bib
+
+dloaddir = /lrde/dload/papers
+dload_DATA = lrde.pdf bib/lrde.bib
+
+
+CLEANFILES = $(papers_DATA) $(dload_DATA) contents.html contents.txt list.bib \
+list.pdf diffs.patch contents.bib contents_bib.html
+
+all: check lrde.pdf
+
+## ------- ##
+## Check.  ##
+## ------- ##
+
+check: check-warning check-bib check-mnt-dload
+
+check-warning:
+	$(QUIET)echo >&2 "***"
+	$(QUIET)echo >&2 "*** To ignore possible checking error, use -k"
+	$(QUIET)echo >&2 "*** But please, first try to fix them"
+	$(QUIET)echo >&2 "***"
+
+check-bib:
+	$(QUIET)LC_ALL=C grep '[^[:print:][:blank:]]' bib/*.bib || exit 0
+
+check-mnt-dload:
+	$(QUIET)(cd $(papersdir) && ls -1 *.pdf) | \
+	   grep -Ev '^lrde(-private)?\.pdf$$' | \
+	   sed -e 's/\.pdf$$//' | \
+	   sort >/tmp/list.pdf
+	$(QUIET)sed -ne '/^@.*{[ \t]*/{s///;s/,//;p}' $(share_bib_dir)/lrde.bib | \
+	   sort >/tmp/list.bib
+	$(QUIET)if cmp -s /tmp/list.pdf /tmp/list.bib; then :; else	\
+	  echo "Files in $(papersdir) not registered in lrde.bib:";	\
+	  comm -23 /tmp/list.pdf /tmp/list.bib;				\
+	  echo;								\
+	  echo "Files not available as PDF in $(papersdir):";		\
+	  comm -13 /tmp/list.pdf /tmp/list.bib;				\
+	  echo;								\
+	  exit 2;							\
+	fi
+
+## ------------------------------- ##
+## lrde.pdf and lrde-private.pdf.  ##
+## ------------------------------- ##
+
+%.txt: $(share_bib_dir)/%.bib
+	rm -f $@.tmp
+	$(QUIET)bibtex2html -q $<
+	$(QUIET)html2text -nobs $*.html | \
+	  sed -e 's/.*\[ bib .*//;/^==*$$/{s/.*//;q;}' >$@.tmp
+	mv $@.tmp $@
+
+# Create a LaTeX document to force the BibTeX check on lrde.bib.
+make_bib = $(share_bin_dir)/make-bib.pl
+%.tex: $(share_bib_dir)/%.bib $(make_bib)
+	$(make_bib) $(share_bib_dir)/$*.bib >$*.tmp
+	mv $*.tmp $*.tex
+
+%-private.tex: $(share_bib_dir)/%.bib $(share_bin_dir)/make-bib.pl
+	$(make_bib) --with-submitted $(share_bib_dir)/$*.bib >$*-private.tmp
+	mv $*-private.tmp $*-private.tex
+
+
+view: lrde.pdf
+	xpdf lrde.pdf
+
+
+## ------------------ ##
+## Wrappers for svn.  ##
+## ------------------ ##
+
+diff:
+	bin/svndiff
+
+up svnupdate:
+	svn up
+
+install: svnupdate $(papers_DATA) $(dload_DATA)
+## The "doc" group rights should allow this.
+	install -m 644 $(dload_DATA) $(dloaddir)
+	install -m 644 $(papers_DATA) $(papersdir)
+
+ci checkin: diff check
+	bin/svnci
+	$(MAKE) $(MAKEFLAGS) install
+
+
+## ----------------------- ##
+## Updating from masters.  ##
+## ----------------------- ##
+
+.PHONY: update
+
+BIB_EXTERNALS = kernighan richie strategoxt
+update:
+	cd bib && chmod a+w $(BIB_EXTERNALS:=.bib)
+	wget http://netlib.bell-labs.com/cm/cs/bib/bwk.bib -O bib/kernighan.bib
+	wget http://cm.bell-labs.com/cm/cs/bib/dmr.bib -O bib/richie.bib
+	wget http://www.cs.uu.nl/~visser/strategoxt/strategoxt.bib -O bib/strategoxt.bib
+# There are many missing commas in this bibtex.
+	cd bib && perl -pi -e 's/(.\})$/\1,/g' $(BIB_EXTERNALS:=.bib)
+# Avoid accidental edition.
+	cd bib && chmod a-w $(BIB_EXTERNALS:=.bib)
diff --git a/doc/share/bin/texi2dvi b/doc/share/bin/texi2dvi
--- a/doc/share/bin/texi2dvi
+++ b/doc/share/bin/texi2dvi
@@ -1,9 +1,9 @@
 #! /bin/sh
 # texi2dvi --- produce DVI (or PDF) files from Texinfo (or (La)TeX) sources.
-# $Id: texi2dvi,v 1.89 2006/06/27 17:01:26 akim Exp $
+# $Id: texi2dvi,v 1.94 2007/01/16 10:01:43 akim Exp $
 #
 # Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2001,
-# 2002, 2003, 2004, 2005, 2006 Free Software Foundation, Inc.
+# 2002, 2003, 2004, 2005, 2006, 2007 Free Software Foundation, Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -35,7 +35,7 @@ unset RUNNING_KSH
 set -e
 
 # This string is expanded by rcs automatically when this file is checked out.
-rcs_revision='$Revision: 1.89 $'
+rcs_revision='$Revision: 1.94 $'
 rcs_version=`set - $rcs_revision; echo $2`
 program=`echo $0 | sed -e 's!.*/!!'`
 version="texi2dvi (GNU Texinfo 4.8) $rcs_version
@@ -71,7 +71,7 @@ General options:
   -D, --debug         turn on shell debugging (set -x)
   -h, --help          display this help and exit successfully
   -o, --output=OFILE  leave output in OFILE (implies --clean);
-                        only one input FILE may be specified in this case
+			only one input FILE may be specified in this case
   -q, --quiet         no output unless errors (implies --batch)
   -s, --silent        same as --quiet
   -v, --version       display version information and exit successfully
@@ -97,10 +97,10 @@ Build modes:
       --tidy           same as --build=tidy
   -c, --clean          same as --build=clean
       --build-dir=DIR  specify where the tidy compilation is performed;
-                         implies --tidy;
-                         defaults to TEXI2DVI_BUILD_DIRECTORY [$build_dir]
+			 implies --tidy;
+			 defaults to TEXI2DVI_BUILD_DIRECTORY [$build_dir]
   --mostly-clean       remove the auxiliary files and directories
-                         but not the output
+			 but not the output
 
 The MODE specifies where the TeX compilation takes place, and, as a
 consequence, how auxiliary files are treated.  The build mode
@@ -108,11 +108,11 @@ can also be set using the environment variable TEXI2DVI_BUILD_MODE.
 
 Valid MODEs are:
   \`local'      compile in the current directory, leaving all the auxiliary
-                 files around.  This is the traditional TeX use.
+		 files around.  This is the traditional TeX use.
   \`tidy'       compile in a local *.t2d directory, where the auxiliary files
-                 are left.  Output files are copied back to the original file.
+		 are left.  Output files are copied back to the original file.
   \`clean'      same as \`tidy', but remove the auxiliary directory afterwards.
-                 Every compilation therefore requires the full cycle.
+		 Every compilation therefore requires the full cycle.
 
 Using the \`tidy' mode brings several advantages:
   - the current directory is not cluttered with plethora of temporary files.
@@ -249,9 +249,9 @@ absolute ()
       ;;
    *) local rel="$orig_pwd/`func_dirname $1`"
       if test -d "$rel"; then
-        (cd "$rel" 2>/dev/null && echo `pwd`/`basename "$1"`);
+	(cd "$rel" 2>/dev/null && echo `pwd`/`basename "$1"`);
       else
-        error 1 "not a directory: $rel"
+	error 1 "not a directory: $rel"
       fi
       ;;
   esac
@@ -467,8 +467,8 @@ done
 absolute_filenames ()
 {
   local replace_empty="-e 's/^$path_sep/EMPTY$path_sep/g' \
-                       -e 's/$path_sep\$/${path_sep}EMPTY/g' \
-                       -e 's/$path_sep$path_sep/${path_sep}EMPTY:/g'"
+		       -e 's/$path_sep\$/${path_sep}EMPTY/g' \
+		       -e 's/$path_sep$path_sep/${path_sep}EMPTY:/g'"
   local res=`echo "$1" | eval sed $replace_empty`
   save_IFS=$IFS
   IFS=$path_sep
@@ -478,13 +478,13 @@ absolute_filenames ()
   do
     case $dir in
       EMPTY)
-        res=$res$path_sep
-        ;;
+	res=$res$path_sep
+	;;
       *)
-        if test -d $dir; then
+	if test -d $dir; then
 	  res=$res$path_sep`absolute "$dir"`
 	fi
-        ;;
+	;;
     esac
   done
   echo "$res"
@@ -594,7 +594,7 @@ xref_file_p ()
   case `sed '1q' $1` in
     "\\input texinfo"*) return 1;;
     [\\''@]*)           return 0;;
-           *)           return 1;;
+	   *)           return 1;;
   esac
 }
 
@@ -621,16 +621,16 @@ generated_files_get ()
     echo $file
     case $in_lang in
       (texinfo)
-        # texindex: texinfo.cp -> texinfo.cps
+	# texindex: texinfo.cp -> texinfo.cps
        if index_file_p $file; then
-         echo ${file}s
+	 echo ${file}s
        fi
        ;;
       (latex)
        # bibtex: *.aux -> *.bbl and *.blg.
-        if aux_file_p $file; then
-          echo $file | sed 's/^\(.*\)\.aux$/\1.bbl/'
-         echo $file | sed 's/^\(.*\)\.aux$/\1.blg/'
+	if aux_file_p $file; then
+	  echo $file | sed 's/^\(.*\)\.aux$/\1.bbl/'
+	 echo $file | sed 's/^\(.*\)\.aux$/\1.blg/'
        fi
        ;;
     esac
@@ -721,12 +721,12 @@ run_tex ()
     latex:dvi)   tex=${LATEX:-latex};;
     latex:pdf)   tex=${PDFLATEX:-pdflatex};;
     texinfo:dvi)
-        # MetaPost also uses the TEX environment variable.  If the user
-        # has set TEX=latex for that reason, don't bomb out.
-        case $TEX in
+	# MetaPost also uses the TEX environment variable.  If the user
+	# has set TEX=latex for that reason, don't bomb out.
+	case $TEX in
 	  *latex) tex=tex;; # don't bother trying to find etex
 	       *) tex=$TEX
-        esac;;
+	esac;;
     texinfo:pdf) tex=$PDFTEX;;
 
     *) error 1 "$0: $out_lang not supported for $in_lang";;
@@ -788,7 +788,7 @@ run_tex ()
       _run_tex_file_name=`basename "$in_input"`
       if test ! -f "$_run_tex_file_name"; then
 	verbose ln -sf "$in_input"
-        ln -sf "$_run_tex_file_name"
+	ln -sf "$_run_tex_file_name"
       fi
       cmd="$cmd '$_run_tex_file_name'"
       ;;
@@ -832,12 +832,17 @@ run_bibtex ()
   esac
 
   # "Citation undefined" is for LaTeX, "Undefined citation" for btxmac.tex.
+  # The no .aux && \bibdata test is also for btxmac, in case it was the
+  # first run of a bibtex-using document.  Otherwise, it's possible that
+  # bibtex would never be run.
   if test -r "$in_noext.aux" \
      && test -r "$in_noext.log" \
      && (grep 'Warning:.*Citation.*undefined' "$in_noext.log" \
-          || grep '.*Undefined citation' "$in_noext.log" \
-          || grep 'No file .*\.bbl\.' "$in_noext.log") \
-        >&6 2>&1; \
+	  || grep '.*Undefined citation' "$in_noext.log" \
+	  || grep 'No file .*\.bbl\.' "$in_noext.log") \
+	  || (grep 'No \.aux file' "$in_noext.log" \
+	      && grep '^\\bibdata' "$in_noext.aux") \
+	>&6 2>&1; \
   then
     for f in $(generated_files_get "$in_noext" bibaux_file_p)
     do
@@ -895,7 +900,7 @@ run_dvipdf ()
     for i in "$DVIPDF" dvipdfmx dvipdfm dvipdf dvi2pdf dvitopdf;
     do
       if findprog $i; then
-        dvipdf=$i
+	dvipdf=$i
       fi
     done
   fi
@@ -1060,7 +1065,7 @@ run_makeinfo ()
     # happens with gettext 0.14.5, at least.
     sed "$comment_iftex" "$command_line_filename" \
       | eval $makeinfo --footnote-style=end -I "$in_dir" $miincludes \
-        -o /dev/null --macro-expand=- \
+	-o /dev/null --macro-expand=- \
       | sed "$uncomment_iftex" >"$in_src"
     # Continue only if everything succeeded.
     if test $? -ne 0 \
@@ -1081,7 +1086,7 @@ insert_commands ()
   case $in_lang in
     latex)   textra_cmd=1i;;
     texinfo) textra_cmd='/^@setfilename/a';;
-    *)       fatal 1 "internal error, unknown language: $in_lang";;
+    *)       error 1 "internal error, unknown language: $in_lang";;
   esac
 
   if test -n "$textra"; then
@@ -1117,7 +1122,7 @@ run_recode ()
 	from=$recode_from
 	to=$encoding
       else
-        from=$encoding
+	from=$encoding
 	to=$texinfo
       fi
       verbose "Recoding from $from to $to."
@@ -1126,10 +1131,10 @@ run_recode ()
       in_rcd=$work_rcd/$in_base
       ensure_dir "$work_rcd"
       if recode "$encoding..$to" <"$in_input" >"$in_rcd" \
-         && test -s "$in_rcd"; then
-        in_input=$in_rcd
+	 && test -s "$in_rcd"; then
+	in_input=$in_rcd
       else
-        verbose "Recoding failed, using original input."
+	verbose "Recoding failed, using original input."
       fi
     fi
   fi
@@ -1193,10 +1198,14 @@ run_hevea ()
 
   verbose "running $run_hevea"
   if eval "$run_hevea" >&5; then
+    # hevea leaves trailing white spaces, this is annoying.
+    case $1 in text|info)
+      perl -pi -e 's/[ \t]+$//g' "$out_base"*;;
+    esac
     case $1 in
     html|text) move_to_dest "$out_base";;
     info) # There can be foo.info-1, foo.info-2 etc.
-               move_to_dest "$out_base"*;;
+	       move_to_dest "$out_base"*;;
     esac
   else
     error 1 "$hevea exited with bad status, quitting."
@@ -1333,15 +1342,15 @@ while test x"$1" != x"$arg_sep"; do
     -@ ) escape=@;;
     # Silently and without documentation accept -b and --b[atch] as synonyms.
     -b | --batch) batch=true;;
-         --build)      shift; build_mode=$1;;
-         --build-dir)  shift; build_dir=$1; build_mode=tidy;;
+	 --build)      shift; build_mode=$1;;
+	 --build-dir)  shift; build_dir=$1; build_mode=tidy;;
     -c | --clean) build_mode=clean;;
     -D | --debug) debug=true;;
-         --dvi)   out_lang=dvi;;
-         --dvipdf)   out_lang=dvipdf;;
+	 --dvi)   out_lang=dvi;;
+	 --dvipdf)   out_lang=dvipdf;;
     -e | -E | --expand) expand=t;;
     -h | --help) echo "$usage"; exit 0;;
-         --html) out_lang=html;;
+	 --html) out_lang=html;;
     -I | --I*)
       shift
       # Use absolute dir names in the includes.
@@ -1357,7 +1366,7 @@ while test x"$1" != x"$arg_sep"; do
       # Make it absolute, just in case we also have --clean, or whatever.
       oname=`absolute "$1"`;;
     -p | --pdf) out_lang=pdf;;
-         --ps)  out_lang=ps;;
+	 --ps)  out_lang=ps;;
     -q | -s | --quiet | --silent) quiet=true; batch=true;;
     -r | --recode) recode=true;;
     --recode-from) shift; recode=true; recode_from="$1";;
@@ -1372,13 +1381,13 @@ while test x"$1" != x"$arg_sep"; do
     --) # What remains are not options.
       shift
       while test x"$1" != x"$arg_sep"; do
-        set dummy ${1+"$@"} "$1"; shift
-        shift
+	set dummy ${1+"$@"} "$1"; shift
+	shift
       done
       break;;
     -*)
       error 1 "Unknown or ambiguous option \`$1'." \
-              "Try \`--help' for more information."
+	      "Try \`--help' for more information."
       ;;
     *) set dummy ${1+"$@"} "$1"; shift;;
    esac
@@ -1505,7 +1514,7 @@ input_file_name_decode ()
       # Let AUC-TeX error parser deal with line numbers.
       line_error=false
       command_line_filename=`\
-        expr X"$command_line_filename" : X'.*input{\([^}]*\)}'`
+	expr X"$command_line_filename" : X'.*input{\([^}]*\)}'`
       ;;
   esac
 
@@ -1518,7 +1527,7 @@ input_file_name_decode ()
   # though the user may be able to reenter a valid filename at the tex
   # prompt (assuming they're attending the terminal), this script won't
   # be able to find the right xref files and so forth.
-  test  -r "$command_line_filename" ||
+  test -r "$command_line_filename" ||
     error 1 "cannot read $command_line_filename, skipping."
 
   # Get the name of the current directory.
@@ -1572,8 +1581,8 @@ for command_line_filename in ${1+"$@"}; do
 	 # file.  The sed expression is fragile if the cwd has
 	 # active characters.
 	 t2ddir=$build_dir/`echo "$out_dir_abs/$out_noext.t2d" |
-             sed "s,^$orig_pwd/,," |
-             sed 's,/,!,g'`
+	     sed "s,^$orig_pwd/,," |
+	     sed 's,/,!,g'`
   esac
   # Remove it at exit if clean mode.
   trap "cleanup" 0 1 2 15
